creation_rules:
  - key_groups:
      - age:
          - age1z7mnu3m88tpf88wvquw9wpf2xdqm5v50l2u85d37gdww25as5d0sf40nfe
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: hosts/eta.yaml$
  - key_groups:
      - age:
          - age18yuzugm0f2l7cc4sdmp5f442af2w897x9l9syeaef3yx3jzc5pjs9zez0f
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: hosts/psi.yaml$
  - key_groups:
      - age:
          - age1u2ymsehnq872lzj086yf87f6k0zq52x66qz84kp3s6crtcxsts3s9fsneq
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: hosts/rho.yaml$
  - key_groups:
      - age:
          - age13v0djuhkmnd06zvct0zc6sddykqpk3j9k8ev5sfgd6gtj82s0avs68psvj
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: hosts/tau.yaml$
  - key_groups:
      - age:
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: modules/minio/secrets.yaml
  - key_groups:
      - age:
          - age18yuzugm0f2l7cc4sdmp5f442af2w897x9l9syeaef3yx3jzc5pjs9zez0f
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: modules/nfs/secrets.yaml
  - key_groups:
      - age:
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: modules/sshd/[^/]+\.yaml$
  - key_groups:
      - age:
          - age18yuzugm0f2l7cc4sdmp5f442af2w897x9l9syeaef3yx3jzc5pjs9zez0f
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: modules/users/xrdp-passwords.yaml
  - key_groups:
      - age:
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: packages/install-iso/secrets.yaml
  - key_groups:
      - age:
          - age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
    path_regex: terraform/secrets.yaml
